name: Package tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Caching composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup ENV
        run: |
          php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Composer Install
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit --log-junit phpunit-report.xml